# Generated by Django 4.0.2 on 2022-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpaths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
